# Site settings
title: Alp Öktem
tagline: "Tech to support linguistic diversity"
email: alp@oktem.me
description: "Blog and research by Alp Öktem on Speech technology, NLP, and social impact"
baseurl: ""
url: "https://alp.oktem.me"
github_username: alpoktem
author: Alp Öktem
lang: en

# Build settings
markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  projects:
    output: true
    permalink: /projects/:path/
  art:
    output: false
    permalink: /art/:path/
  teaching:
    output: false
    permalink: /teaching/:path/
  publications:
    output: true
    permalink: /publications/:path/


