# Site settings
title: Alp Öktem
email: alp@oktem.me
description: Personal page of Alp Öktem
baseurl: ""
url: "https://alp.oktem.me"
github_username:  alpoktem

# Build settings
markdown: kramdown
highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  projects:
    output: true
    permalink: /projects/:path/
  art:
    output: false
    permalink: /art/:path/
  teaching:
    output: false
    permalink: /teaching/:path/
  publications:
    output: true
    permalink: /publications/:path/


